const $=x=>document.getElementById(x);let api=localStorage.getItem("simeter_api_url")||"",gps={},meters=[],hist=[],qr=null;
document.addEventListener("DOMContentLoaded",()=>{ $("api").value=api;tabs();events();loadLocal();render();navigator.serviceWorker?.register("sw.js")});
function tabs(){document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{stop();document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.t).classList.add("active")})}
function events(){$("save").onclick=()=>{api=$("api").value.trim();localStorage.setItem("simeter_api_url",api);$("apiMsg").textContent="URL disimpan."};$("test").onclick=test;$("scan").onclick=start;$("stop").onclick=stop;$("meter").onchange=()=>lookup($("meter").value.trim());$("getgps").onclick=getgps;$("foto").onchange=preview;$("form").onsubmit=save;$("refreshM").onclick=loadM;$("refreshH").onclick=loadH;$("searchM").oninput=renderM;$("searchH").oninput=renderH}
async function test(){if(!api)return $("apiMsg").textContent="Isi URL /exec dulu.";try{$("apiMsg").textContent=(await(await fetch(api+"?action=ping")).json()).message}catch(e){$("apiMsg").textContent="Gagal: "+e.message}}
async function start(){if(!api)return $("scanMsg").textContent="Isi URL /exec dulu."; $("reader").classList.remove("hide");$("scan").classList.add("hide");$("stop").classList.remove("hide");qr=new Html5Qrcode("reader");try{await qr.start({facingMode:"environment"},{fps:10,qrbox:{width:250,height:150}},async t=>{await stop();$("meter").value=t.trim();await lookup(t.trim())})}catch(e){$("scanMsg").textContent="Kamera gagal dibuka. Izinkan kamera dan gunakan HTTPS.";await stop()}}
async function stop(){if(qr){try{await qr.stop()}catch{}try{await qr.clear()}catch{}qr=null}$("reader").classList.add("hide");$("scan").classList.remove("hide");$("stop").classList.add("hide")}
async function lookup(n){if(!n||!api)return;try{let j=await(await fetch(api+"?action=meter&nomorMeter="+encodeURIComponent(n))).json();if(j.meter){$("id").value=j.meter.idPelanggan||"";$("meter").value=j.meter.nomorMeter||n;$("name").textContent=j.meter.namaPelanggan||"-";$("address").textContent=j.meter.alamat||"-";$("customer").classList.remove("hide");$("scanMsg").textContent="Data meter ditemukan."}else{$("customer").classList.add("hide");$("scanMsg").textContent="Nomor meter tidak ditemukan di MASTER_METER."}}catch(e){$("scanMsg").textContent="Gagal mencari: "+e.message}}
function getgps(){navigator.geolocation?.getCurrentPosition(p=>{gps={lat:p.coords.latitude.toFixed(6),lng:p.coords.longitude.toFixed(6),accuracy:p.coords.accuracy.toFixed(1)};$("gps").textContent=`${gps.lat}, ${gps.lng} (±${gps.accuracy}m)`},e=>$("msg").textContent="GPS: "+e.message,{enableHighAccuracy:true,timeout:15000})}
function preview(){let f=$("foto").files[0];if(!f)return;let r=new FileReader();r.onload=e=>{$("preview").src=e.target.result;$("preview").classList.remove("hide")};r.readAsDataURL(f)}
async function save(e){e.preventDefault();let f=$("foto").files[0],photo=f?await image(f):"";let d={action:"saveMaintenance",timestamp:new Date().toISOString(),idPelanggan:$("id").value.trim(),nomorMeter:$("meter").value.trim(),namaPelanggan:$("name").textContent,alamat:$("address").textContent,jenis:$("jenis").value,kondisi:$("kondisi").value,stand:$("stand").value,keterangan:$("ket").value,latitude:gps.lat||"",longitude:gps.lng||"",accuracy:gps.accuracy||"",foto:photo};try{let j=await post(d);if(j.ok===false)throw Error(j.error||"Gagal");$("msg").textContent="✓ Data berhasil disimpan ke Google Sheets.";hist.unshift(d);localStorage.setItem("simeter_history",JSON.stringify(hist));render()}catch(x){d.pending=true;hist.unshift(d);localStorage.setItem("simeter_history",JSON.stringify(hist));$("msg").textContent="Disimpan offline: "+x.message}e.target.reset();gps={};$("gps").textContent="Belum diambil";$("customer").classList.add("hide");$("preview").classList.add("hide")}
async function post(d){let r=await fetch(api,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(d)});return r.json()}
async function loadM(){if(!api)return;let j=await(await fetch(api+"?action=getMeters")).json();meters=j.data||[];localStorage.setItem("simeter_meters",JSON.stringify(meters));renderM()}
async function loadH(){if(!api)return;let j=await(await fetch(api+"?action=getHistory")).json();hist=j.data||[];localStorage.setItem("simeter_history",JSON.stringify(hist));renderH()}
function loadLocal(){try{meters=JSON.parse(localStorage.getItem("simeter_meters")||"[]");hist=JSON.parse(localStorage.getItem("simeter_history")||"[]")}catch{}}
function render(){renderM();renderH()}
function renderM(){let q=($("searchM").value||"").toLowerCase();$("meters").innerHTML=meters.filter(x=>JSON.stringify(x).toLowerCase().includes(q)).map(x=>`<div class=item><b>${esc(x.idPelanggan)}</b><small>Meter: ${esc(x.nomorMeter)}<br>Nama: ${esc(x.namaPelanggan)}<br>Alamat: ${esc(x.alamat)}</small></div>`).join("")||"<p>Belum ada data.</p>"}
function renderH(){let q=($("searchH").value||"").toLowerCase();$("hist").innerHTML=hist.filter(x=>JSON.stringify(x).toLowerCase().includes(q)).map(x=>`<div class=item><b>${esc(x.idPelanggan)} — ${esc(x.jenis)}</b><small>Meter: ${esc(x.nomorMeter)}<br>${new Date(x.timestamp||Date.now()).toLocaleString("id-ID")}<br>${x.pending?"⏳ Offline":"✓ Terkirim"}</small></div>`).join("")||"<p>Belum ada riwayat.</p>"}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function image(f){return new Promise((res,rej)=>{let r=new FileReader();r.onload=()=>{let i=new Image;i.onload=()=>{let m=1200,w=i.width,h=i.height;if(w>m){h=h*m/w;w=m}let c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(i,0,0,w,h);res(c.toDataURL("image/jpeg",.75))};i.src=r.result};r.onerror=rej;r.readAsDataURL(f)})}