let AUTH=JSON.parse(localStorage.getItem("simeter_auth")||"null");
let ROLE=AUTH?.user?.role||"",API=localStorage.getItem("simeter_api_url")||"",history=[],queue=[],tasks=[],users=[],gps={},photo="",scanner=null;
const $=id=>document.getElementById(id), DEFAULT_INTERVAL=30;
document.addEventListener("DOMContentLoaded",()=>{bind();loadLocal();if($("apiUrl"))$("apiUrl").value=API;if(AUTH)showApp();else showLogin();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});});
function bind(){
 $("loginBtn").onclick=loginUser;$("saveLoginApi").onclick=()=>{API=$("loginApi").value.trim();localStorage.setItem("simeter_api_url",API);$("loginStatus").textContent=API?"URL tersimpan. Silakan login.":"URL belum diisi."};$("togglePass").onclick=()=>{$("loginPass").type=$("loginPass").type==="password"?"text":"password"};$("logoutBtn").onclick=logout;
 document.querySelectorAll("[data-page]").forEach(x=>x.onclick=()=>go(x.dataset.page));$("more").onclick=()=>$('moreMenu').classList.remove('hidden');$("closeMore").onclick=closeMore;$('moreMenu').querySelector('.shade').onclick=closeMore;
 $("assetSearch").oninput=renderAssets;$("reloadAssets").onclick=loadHistory;$("backAssets").onclick=()=>go('assets');$("historySearch").oninput=renderHistory;$("reloadHistory").onclick=loadHistory;
 $("scanStart").onclick=startScanner;$("scanStop").onclick=stopScanner;$("useScanned").onclick=()=>{$("nomorMeter").value=$("meterNo").value.trim();go('maintenance')};$("gpsBtn").onclick=getGPS;$("foto").onchange=photoPreview;
 $("maintForm").onsubmit=saveMaintenance;$("resetForm").onclick=resetForm;$("intervalHari").oninput=updateDueDate;
 $("saveApi").onclick=saveAPI;$("syncBtn").onclick=syncAll;$("saveTask").onclick=saveTask;$("reloadTasks").onclick=loadTasks;$("saveUser").onclick=saveUser;$("saveSettings").onclick=saveSettings;
 $("notifBtn").onclick=requestNotifications;$("notifProfileBtn").onclick=requestNotifications;window.addEventListener('online',()=>{updateNet();syncAll()});window.addEventListener('offline',updateNet);setInterval(checkNotifications,10*60*1000);
}
function showLogin(){$('loginPage').classList.remove('hidden');$('appShell').classList.add('hidden')}
function showApp(){$('loginPage').classList.add('hidden');$('appShell').classList.remove('hidden');ROLE=AUTH.user.role;$('userRole').textContent=`${AUTH.user.nama} · ${ROLE}`;$('profileName').textContent=AUTH.user.nama;$('profileRole').textContent=ROLE;$('profileUnit').textContent=AUTH.user.unit||'-';applyRoleAccess();loadLocal();syncAll();checkNotifications()}
async function loginUser(){const u=$('loginUser').value.trim(),p=$('loginPass').value;if(!u||!p){$('loginStatus').textContent='Username dan kata sandi wajib diisi.';return}if(!API){$('loginStatus').textContent='Masukkan URL Web App Apps Script terlebih dahulu.';return}$('loginBtn').disabled=true;$('loginStatus').textContent='Memeriksa...';try{const d=await getPublic('login',{username:u,password:p});if(!d.ok)throw Error(d.error||'Login gagal');AUTH=d;ROLE=d.user.role;localStorage.setItem('simeter_auth',JSON.stringify(AUTH));$('loginPass').value='';showApp()}catch(e){$('loginStatus').textContent=e.message}finally{$('loginBtn').disabled=false}}
function logout(){AUTH=null;ROLE='';localStorage.removeItem('simeter_auth');showLogin()}
function can(...r){return r.includes(ROLE)}
function applyRoleAccess(){const map={assets:['SUPER_ADMIN','ADMIN','PETUGAS','SUPERVISOR','VIEWER'],scan:['SUPER_ADMIN','ADMIN','PETUGAS'],maintenance:['SUPER_ADMIN','ADMIN','PETUGAS'],history:['SUPER_ADMIN','ADMIN','PETUGAS','SUPERVISOR','VIEWER'],tasks:['SUPER_ADMIN','ADMIN','PETUGAS','SUPERVISOR'],admin:['SUPER_ADMIN','ADMIN'],profile:['SUPER_ADMIN','ADMIN','PETUGAS','SUPERVISOR','VIEWER'],settings:['SUPER_ADMIN']};document.querySelectorAll('[data-page]').forEach(b=>{const p=b.dataset.page;b.style.display=(!map[p]||map[p].includes(ROLE))?'':'none'});$('taskCreate').style.display=can('SUPER_ADMIN','ADMIN','SUPERVISOR')?'':'none'}
function closeMore(){$('moreMenu').classList.add('hidden')}
function go(id){closeMore();const rules={assets:['SUPER_ADMIN','ADMIN','PETUGAS','SUPERVISOR','VIEWER'],scan:['SUPER_ADMIN','ADMIN','PETUGAS'],maintenance:['SUPER_ADMIN','ADMIN','PETUGAS'],history:['SUPER_ADMIN','ADMIN','PETUGAS','SUPERVISOR','VIEWER'],tasks:['SUPER_ADMIN','ADMIN','PETUGAS','SUPERVISOR'],admin:['SUPER_ADMIN','ADMIN'],profile:['SUPER_ADMIN','ADMIN','PETUGAS','SUPERVISOR','VIEWER'],settings:['SUPER_ADMIN']};if(rules[id]&&!rules[id].includes(ROLE)){alert('Anda tidak memiliki hak akses.');return}document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));$(id).classList.add('active');scrollTo(0,0);if(id==='assets')renderAssets();if(id==='tasks')loadTasks();if(id==='admin'){loadUsers();loadSettings()}}
function loadLocal(){try{history=JSON.parse(localStorage.getItem('history')||'[]');queue=JSON.parse(localStorage.getItem('queue')||'[]');tasks=JSON.parse(localStorage.getItem('tasks')||'[]')}catch(e){}renderAll()}
function persist(){localStorage.setItem('history',JSON.stringify(history));localStorage.setItem('queue',JSON.stringify(queue));localStorage.setItem('tasks',JSON.stringify(tasks))}
function updateNet(){$('net').textContent=navigator.onLine?'● Online':'● Offline';$('net').style.color=navigator.onLine?'#dfffe9':'#ffd4d4'}
function renderAll(){renderHistory();renderRecent();renderAssets();renderTasks();updateStats();updateNet()}
function updateStats(){const a=getAssets();$('sMeters').textContent=a.length;$('sMaint').textContent=history.length;$('sDue').textContent=a.filter(x=>x.days!==null&&x.days<=0).length;$('sTasks').textContent=tasks.filter(x=>x.status!=='Selesai').length}
function renderRecent(){$('recent').innerHTML=history.slice(0,5).map(itemHTML).join('')||'<div class="item">Belum ada maintenance.</div>'}
function renderHistory(){const q=($('historySearch').value||'').toLowerCase();const a=history.filter(x=>Object.values(x).join(' ').toLowerCase().includes(q));$('historyList').innerHTML=a.map(itemHTML).join('')||'<div class="item">Belum ada riwayat.</div>'}
function itemHTML(x){return `<div class="item"><b>${esc(x.nomorMeter||'-')} ${x.pending?'⚠️':''}</b><small>${esc(x.namaPelanggan||'-')} · ${esc(x.jenis||'Maintenance')}<br>${esc(x.tanggal||x.timestamp||'')} · ${esc(x.petugas||'')}</small></div>`}
function parseDate(v){if(!v)return null;let d=new Date(v);if(!isNaN(d))return d;let m=String(v).match(/(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})/);return m?new Date(+m[3],+m[2]-1,+m[1]):null}
function fmtDate(d){return d?d.toLocaleDateString('id-ID',{day:'2-digit',month:'2-digit',year:'numeric'}):'-'}
function getAssets(){const map={};history.forEach(x=>{const n=String(x.nomorMeter||'').trim();if(!n)return;if(!map[n])map[n]={nomorMeter:n,idPelanggan:x.idPelanggan||'',namaPelanggan:x.namaPelanggan||'',alamat:x.alamat||'',rows:[]};map[n].rows.push(x);});return Object.values(map).map(a=>{a.rows.sort((x,y)=>new Date(y.timestamp||y.tanggal)-new Date(x.timestamp||x.tanggal));let last=a.rows[0],interval=Number(last.intervalHari||DEFAULT_INTERVAL)||DEFAULT_INTERVAL,ld=parseDate(last.timestamp||last.tanggal),due=ld?new Date(ld.getTime()+interval*86400000):null,today=new Date();today.setHours(0,0,0,0);let dd=due?new Date(due):null;if(dd)dd.setHours(0,0,0,0);a.last=last;a.interval=interval;a.lastDate=ld;a.due=due;a.days=dd?Math.ceil((dd-today)/86400000):null;a.status=a.days===null?'Belum Ada':a.days<0?'Jatuh Tempo':a.days<=7?'Segera Jatuh Tempo':/rusak|tidak normal/i.test(last.kondisi||'')?'Tidak Normal':'Normal';return a}).sort((a,b)=>(a.days??99999)-(b.days??99999))}
function renderAssets(){const q=($('assetSearch').value||'').toLowerCase();const a=getAssets().filter(x=>(x.nomorMeter+' '+x.idPelanggan+' '+x.namaPelanggan+' '+x.alamat).toLowerCase().includes(q));$('assetList').innerHTML=a.map(x=>`<button class="asset-card" onclick="openAsset('${attr(x.nomorMeter)}')"><div class="asset-top"><div><b>${esc(x.namaPelanggan||'Tanpa Nama')}</b><small>${esc(x.nomorMeter)}</small></div><span class="badge ${x.days!==null&&x.days<0?'danger':x.days!==null&&x.days<=7?'warn':'normal'}">● ${esc(x.status)}</span></div><div class="asset-grid"><div><small>Interval</small><b>${x.interval} hari</b></div><div><small>Maintenance Terakhir</small><b>${fmtDate(x.lastDate)}</b></div><div><small>Jadwal Berikutnya</small><b>${fmtDate(x.due)}</b></div><div><small>Hitung Mundur</small><b>${x.days===null?'-':x.days<0?Math.abs(x.days)+' hari terlambat':x.days+' hari lagi'}</b></div></div></button>`).join('')||'<div class="item">Belum ada data aset.</div>'}
function openAsset(n){const x=getAssets().find(a=>a.nomorMeter===String(n));if(!x)return;$('assetDetailCard').innerHTML=`<div class="asset-detail"><div class="asset-top"><div><h2>${esc(x.namaPelanggan||'Tanpa Nama')}</h2><small>${esc(x.nomorMeter)}</small></div><span class="badge ${x.days!==null&&x.days<0?'danger':x.days!==null&&x.days<=7?'warn':'normal'}">● ${esc(x.status)}</span></div><div class="asset-grid"><div><small>ID Pelanggan</small><b>${esc(x.idPelanggan||'-')}</b></div><div><small>Alamat</small><b>${esc(x.alamat||'-')}</b></div><div><small>Interval Maintenance</small><b>${x.interval} hari</b></div><div><small>Maintenance Terakhir</small><b>${fmtDate(x.lastDate)}</b></div><div><small>Jadwal Berikutnya</small><b>${fmtDate(x.due)}</b></div><div><small>Hitung Mundur</small><b class="${x.days!==null&&x.days<0?'due-red':x.days!==null&&x.days<=7?'due-yellow':'due-green'}">${x.days===null?'-':x.days<0?Math.abs(x.days)+' hari terlambat':x.days+' hari lagi'}</b></div></div><div class="grid2"><input id="editInterval" type="number" min="1" value="${x.interval}" placeholder="Interval hari"><button class="primary" onclick="setIntervalAsset('${attr(x.nomorMeter)}')">Simpan Interval</button></div><button class="primary" onclick="useAsset('${attr(x.nomorMeter)}')">🛠️ Buat Pemeliharaan</button></div>`;$('assetHistory').innerHTML=x.rows.map(itemHTML).join('');go('assetDetail')}
function useAsset(n){go('maintenance');$('nomorMeter').value=n;const x=getAssets().find(a=>a.nomorMeter===String(n));if(x){$('idPelanggan').value=x.idPelanggan||'';$('custName').value=x.namaPelanggan||'';$('custAddress').value=x.alamat||'';$('intervalHari').value=x.interval;updateDueDate()}}
async function setIntervalAsset(n){const v=Number($('editInterval').value);if(!v)return;try{const d=await post({token:AUTH.token,action:'setAssetInterval',nomorMeter:n,intervalHari:v});if(!d.ok)throw Error(d.error);alert('Interval berhasil diubah menjadi '+v+' hari');await loadHistory();openAsset(n)}catch(e){alert(e.message)}}
function updateDueDate(){const d=new Date();d.setDate(d.getDate()+Number($('intervalHari').value||DEFAULT_INTERVAL));$('nextDue').value=d.toISOString().slice(0,10)}
function getGPS(){if(!navigator.geolocation){$('gpsStatus').textContent='GPS tidak didukung';return}$('gpsStatus').textContent='Mengambil lokasi...';navigator.geolocation.getCurrentPosition(p=>{gps={latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy};$('gpsStatus').textContent=`${gps.latitude.toFixed(6)}, ${gps.longitude.toFixed(6)} ±${gps.accuracy.toFixed(1)} m`},e=>$('gpsStatus').textContent='Gagal: '+e.message,{enableHighAccuracy:true,timeout:15000})}
function photoPreview(){const f=$('foto').files[0];if(!f)return;const r=new FileReader();r.onload=e=>{photo=e.target.result;$('fotoPreview').src=photo;$('fotoPreview').classList.remove('hidden')};r.readAsDataURL(f)}
async function saveMaintenance(e){e.preventDefault();const d={token:AUTH.token,action:'saveMaintenance',timestamp:new Date().toISOString(),tanggal:new Date().toLocaleDateString('id-ID'),idPelanggan:$('idPelanggan').value,nomorMeter:$('nomorMeter').value,namaPelanggan:$('custName').value,alamat:$('custAddress').value,jenis:$('jenis').value,intervalHari:Number($('intervalHari').value)||DEFAULT_INTERVAL,kondisi:$('kondisi').value,kondisiSegel:$('segel').value,stand:$('stand').value,hasilPemeriksaan:$('hasil').value,keterangan:$('keterangan').value,petugas:AUTH.user.nama,latitude:gps.latitude||'',longitude:gps.longitude||'',accuracy:gps.accuracy||'',foto:photo};if(!d.nomorMeter){$('saveStatus').textContent='Nomor meter wajib diisi.';return}try{if(!API||!navigator.onLine)throw Error('offline');const x=await post(d);if(!x.ok)throw Error(x.error);$('saveStatus').textContent='✓ Data tersimpan di Google Sheets';await loadHistory();resetForm()}catch(e){d.pending=true;queue.push(d);history.unshift(d);persist();$('saveStatus').textContent='⚠ Offline: tersimpan di perangkat dan akan disinkronkan saat online.';renderAll()}}
function resetForm(){$('maintForm').reset();$('intervalHari').value=DEFAULT_INTERVAL;$('fotoPreview').classList.add('hidden');photo='';gps={};updateDueDate()}
async function loadHistory(){try{const d=await get('getHistory');history=d.data||[];persist();renderAll();checkNotifications()}catch(e){}}
async function loadTasks(){try{const d=await get('getTasks');tasks=d.data||[];persist();renderTasks()}catch(e){renderTasks()}}
function renderTasks(){const mine=can('PETUGAS')?tasks.filter(t=>t.untukUsername===AUTH.user.username):tasks;const sorted=mine.sort((a,b)=>new Date(a.batasWaktu||'9999')-new Date(b.batasWaktu||'9999'));$('taskList').innerHTML=sorted.map(t=>`<div class="task-card"><div class="task-top"><div><b>${esc(t.judul)}</b><small>${esc(t.nomorMeter||'-')} · Untuk: ${esc(t.untukNama||t.untukUsername)}</small></div><span class="task-status ${t.status==='Selesai'?'':'open'}">${esc(t.status)}</span></div><small>${esc(t.deskripsi||'')}<br>Prioritas: ${esc(t.prioritas)} · Batas: ${esc(t.batasWaktu||'-')}</small>${t.status!=='Selesai'&&can('PETUGAS')?`<button class="primary" onclick="completeTask('${attr(t.idTugas)}')">✓ Tandai Selesai</button>`:''}</div>`).join('')||'<div class="item">Belum ada tugas.</div>'}
async function completeTask(id){try{const d=await post({token:AUTH.token,action:'updateTaskStatus',idTugas:id,status:'Selesai',catatan:'Diselesaikan dari aplikasi'});if(!d.ok)throw Error(d.error);await loadTasks();checkNotifications()}catch(e){alert(e.message)}}
async function saveTask(){if(!can('SUPER_ADMIN','ADMIN','SUPERVISOR'))return;const d={token:AUTH.token,action:'saveTask',untukUsername:$('taskAssignee').value,nomorMeter:$('taskMeter').value,judul:$('taskTitle').value,deskripsi:$('taskDesc').value,prioritas:$('taskPriority').value,batasWaktu:$('taskDue').value};if(!d.untukUsername||!d.judul){$('taskStatus').textContent='Petugas dan judul wajib diisi.';return}try{const x=await post(d);if(!x.ok)throw Error(x.error);$('taskStatus').textContent='✓ Tugas berhasil diberikan';$('taskTitle').value='';$('taskDesc').value='';await loadTasks();checkNotifications()}catch(e){$('taskStatus').textContent=e.message}}
async function loadUsers(){try{const d=await get('getUsers');users=d.data||[];if(can('SUPER_ADMIN','ADMIN','SUPERVISOR')){$('taskAssignee').innerHTML=users.filter(u=>u.aktif&&u.role==='PETUGAS').map(u=>`<option value="${attr(u.username)}">${esc(u.nama)} · ${esc(u.unit||'')}</option>`).join('')||'<option value="">Belum ada petugas</option>'}$('userList').innerHTML=users.map(u=>`<div class="item"><b>${esc(u.nama)} · ${esc(u.role)}</b><small>${esc(u.username)} · ${esc(u.unit)} · ${esc(u.aktif)}</small></div>`).join('')}catch(e){}}
async function saveUser(){if(!can('SUPER_ADMIN','ADMIN'))return;const d={token:AUTH.token,action:'saveUser',username:$('newUsername').value.trim(),nama:$('newName').value.trim(),password:$('newPassword').value,role:$('newRole').value,unit:$('newUnit').value,aktif:'Ya'};try{const x=await post(d);if(!x.ok)throw Error(x.error);$('userStatus').textContent='✓ Pengguna dibuat';await loadUsers()}catch(e){$('userStatus').textContent=e.message}}
async function loadSettings(){try{const d=await get('getSettings');$('defaultInterval').value=d.defaultInterval||DEFAULT_INTERVAL;$('notifyDays').value=d.notifyDays??7}catch(e){}}
async function saveSettings(){try{const x=await post({token:AUTH.token,action:'saveSettings',defaultInterval:Number($('defaultInterval').value)||DEFAULT_INTERVAL,notifyDays:Number($('notifyDays').value)||0});$('settingsStatus').textContent=x.ok?'✓ Pengaturan tersimpan':x.error}catch(e){$('settingsStatus').textContent=e.message}}
async function saveAPI(){API=$('apiUrl').value.trim();localStorage.setItem('simeter_api_url',API);try{const d=await getPublic('ping');$('apiStatus').textContent=d.message||'SIMETER API aktif';syncAll()}catch(e){$('apiStatus').textContent='Gagal koneksi: '+e.message}}
async function getPublic(action,params={}){if(!API)throw Error('URL API belum diatur');let u=API+'?action='+encodeURIComponent(action);for(const[k,v]of Object.entries(params))u+='&'+encodeURIComponent(k)+'='+encodeURIComponent(v);const r=await fetch(u+'&t='+Date.now(),{cache:'no-store'});return r.json()}
async function get(action,params={}){let u=API+'?action='+encodeURIComponent(action)+'&token='+encodeURIComponent(AUTH?.token||'');for(const[k,v]of Object.entries(params))u+='&'+encodeURIComponent(k)+'='+encodeURIComponent(v);const r=await fetch(u+'&t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
async function post(data){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(data)});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
async function syncAll(){if(!API||!navigator.onLine)return;try{await loadHistory();await loadTasks();await loadUsers();await syncQueue()}catch(e){}}
async function syncQueue(){if(!API||!navigator.onLine||!queue.length)return;let left=[];for(const d of queue){try{const x=await post({...d,pending:false});if(!x.ok)throw Error(x.error)}catch(e){left.push(d)}}queue=left;persist();$('syncStatus').textContent=left.length?`Masih ${left.length} data belum tersinkron.`:'✓ Semua data offline tersinkron.';updateStats()}
async function checkNotifications(){if(!AUTH||!API||!navigator.onLine)return;try{const d=await get('getNotifications');const a=d.data||[];$('notifPanel').innerHTML=a.slice(0,5).map(n=>`<div class="notice ${n.level==='danger'?'danger':''}"><b>${esc(n.title)}</b><span>${esc(n.message)}</span></div>`).join('');$('sDue').textContent=a.filter(n=>n.type==='asset').length;if(a.length&&Notification.permission==='granted'){a.slice(0,3).forEach(n=>{if(!sessionStorage.getItem('notif_'+n.key)){new Notification(n.title,{body:n.message});sessionStorage.setItem('notif_'+n.key,'1')}})}}catch(e){}}
async function requestNotifications(){if(!('Notification'in window)){alert('Browser tidak mendukung notifikasi.');return}const p=await Notification.requestPermission();$('notifState').textContent=p==='granted'?'✓ Notifikasi aktif':'Notifikasi belum diizinkan';$('notifBtn').classList.toggle('notif-btn-on',p==='granted');checkNotifications()}
function updateDueDate(){const d=new Date();d.setDate(d.getDate()+Number($('intervalHari').value||DEFAULT_INTERVAL));$('nextDue').value=d.toISOString().slice(0,10)}
async function startScanner(){if(typeof Html5Qrcode==='undefined'){$('scanStatus').textContent='Scanner belum siap.';return}$('scanStart').classList.add('hidden');$('scanStop').classList.remove('hidden');scanner=new Html5Qrcode('reader');try{await scanner.start({facingMode:'environment'},{fps:10,qrbox:{width:280,height:160}},async text=>{let n=(String(text).match(/\d{8,20}/)||[String(text)])[0];await stopScanner();$('meterNo').value=n;$('nomorMeter').value=n;go('maintenance')})}catch(e){$('scanStatus').textContent='Kamera gagal: '+e.message;stopScanner()}}
async function stopScanner(){if(scanner){try{await scanner.stop()}catch(e){}try{await scanner.clear()}catch(e){}scanner=null}$('scanStart').classList.remove('hidden');$('scanStop').classList.add('hidden')}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function attr(v){return String(v??'').replace(/'/g,'&#39;')}
