let API=localStorage.getItem("simeter_api_url")||"",meters=[],history=[],gps={},photo="",scanner=null;
const $=x=>document.getElementById(x);
document.addEventListener("DOMContentLoaded",()=>{
 if($("apiUrl"))$("apiUrl").value=API;
 document.querySelectorAll("[data-screen]").forEach(b=>b.onclick=()=>go(b.dataset.screen));
 $("assetRefresh").onclick=loadMeters;$("historyRefresh").onclick=loadHistory;$("sync").onclick=sync;
 $("saveApi").onclick=saveApi;$("findMeter").onclick=()=>lookup($("manualMeter").value.trim());
 $("manualMeter").onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();lookup($("manualMeter").value.trim())}};
 $("assetSearch").oninput=renderAssets;$("startScan").onclick=startScan;$("stopScan").onclick=stopScan;
 $("getGps").onclick=getGps;$("fFoto").onchange=previewPhoto;$("maintenanceForm").onsubmit=saveRecord;
 $("moreBtn").onclick=()=>$("otherMenu").classList.remove("hidden");$("closeModal").onclick=closeModal;
 $("otherMenu").querySelector(".modal-bg").onclick=closeModal;
 loadLocal();sync();setNav("home");
 if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});
});
function closeModal(){$("otherMenu").classList.add("hidden")}
function go(id){
 closeModal();document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));$(id).classList.add("active");
 const titles={home:"Ringkasan",assets:"Aset",assetDetail:"Aset",scan:"Scan",tasks:"Tugas",admin:"Admin",profile:"Profil",settings:"Pengaturan"};
 $("headerTitle").textContent=titles[id]||"SIMETER";setNav(id);scrollTo(0,0);
 if(id==="assets")loadMeters();if(id==="tasks")loadHistory();
}
function setNav(id){document.querySelectorAll(".bottom button").forEach(b=>b.classList.toggle("active",b.dataset.screen===id||((id==="assetDetail"||id==="assets")&&b.dataset.screen==="assets")))}
async function saveApi(){API=$("apiUrl").value.trim();localStorage.setItem("simeter_api_url",API);if(!API){$("apiMsg").textContent="URL belum diisi";return}try{let r=await fetch(API+"?action=ping&t="+Date.now()),d=await r.json();$("apiMsg").textContent=d.message||"SIMETER API aktif";sync()}catch(e){$("apiMsg").textContent="Koneksi gagal: "+e.message}}
async function sync(){if(!API)return;await Promise.allSettled([loadMeters(),loadHistory()]);summary()}
async function loadMeters(){if(!API)return;try{let r=await fetch(API+"?action=getMeters&t="+Date.now(),{cache:"no-store"}),d=await r.json();meters=d.data||[];localStorage.setItem("simeter_meters",JSON.stringify(meters));renderAssets();summary()}catch(e){$("assetList").innerHTML='<div class="item">Gagal memuat data meter.<br>'+esc(e.message)+'</div>'}}
async function loadHistory(){if(!API)return;try{let r=await fetch(API+"?action=getHistory&t="+Date.now(),{cache:"no-store"}),d=await r.json();history=d.data||[];localStorage.setItem("simeter_history",JSON.stringify(history));renderTasks();summary()}catch(e){}}
function loadLocal(){try{meters=JSON.parse(localStorage.getItem("simeter_meters")||"[]");history=JSON.parse(localStorage.getItem("simeter_history")||"[]")}catch(e){}renderAssets();renderTasks();summary()}
function summary(){$("totalAssets").textContent=meters.length;$("badAssets").textContent=history.filter(x=>/rusak|tidak normal/i.test(x.kondisi||"")).length;$("openTasks").textContent=history.filter(x=>x.pending).length;$("dueAssets").textContent=0;$("recent").innerHTML=history.slice(0,3).map(x=>'<div class="item"><b>'+esc(x.nomorMeter||"-")+'</b><small>'+esc(x.namaPelanggan||"")+" · "+esc(x.tanggal||"")+'</small></div>').join("")||'<div class="item">Belum ada maintenance.</div>'}
function renderAssets(){let q=($("assetSearch")?.value||"").toLowerCase(),a=meters.filter(x=>JSON.stringify(x).toLowerCase().includes(q));$("assetList").innerHTML=a.length?a.map(x=>'<div class="item"><b>'+esc(x.namaPelanggan||"Tanpa Nama")+'</b><small>'+esc(x.nomorMeter)+' · '+esc(x.idPelanggan)+'<br>'+esc(x.alamat)+'</small><br><button class="secondary" onclick="openAsset(\''+escAttr(x.nomorMeter)+'\')">Lihat Aset</button></div>').join(""):'<div class="item">Data meter kosong. Pastikan MASTER_METER terisi dan URL API benar.</div>'}
function renderTasks(){$("taskList").innerHTML=history.length?history.map(x=>'<div class="item"><b>'+esc(x.nomorMeter||"-")+'</b><small>'+esc(x.namaPelanggan||"")+" · "+esc(x.tanggal||x.timestamp||"")+(x.pending?" · Offline":"")+'</small></div>').join(""):'<div class="item">Belum ada tugas.</div>'}
function openAsset(n){let m=meters.find(x=>String(x.nomorMeter).trim()===String(n).trim());if(!m)return;go("assetDetail");$("detailName").textContent=m.namaPelanggan||"Aset";$("detailCrumb").textContent=m.nomorMeter;$("detailMeter").textContent=m.nomorMeter||"-";let h=history.filter(x=>String(x.nomorMeter).trim()===String(n).trim());$("detailHistory").innerHTML=h.length?h.map(x=>'<div class="item"><b>'+esc(x.petugas||"Teknisi")+' <span class="normal">● Normal</span></b><small>'+esc(x.keterangan||x.hasilPemeriksaan||"Maintenance")+'<br>'+esc(x.tanggal||x.timestamp||"")+'</small></div>').join(""):'<div class="item">Belum ada riwayat maintenance.</div>';let last=h[0]?.tanggal||"-";$("detailLast").textContent=last;let d=new Date();d.setDate(d.getDate()+30);$("detailNext").textContent=d.toISOString().slice(0,10)}
async function lookup(n){n=String(n||"").trim();if(!n||!API){$("scanMsg").textContent="Isi URL API di Pengaturan.";return}try{let r=await fetch(API+"?action=meter&nomorMeter="+encodeURIComponent(n)+"&t="+Date.now()),d=await r.json();if(d.ok&&d.meter){let m=d.meter;$("fId").value=m.idPelanggan||"";$("fMeter").value=m.nomorMeter||n;$("customerName").textContent=m.namaPelanggan||"-";$("customerAddress").textContent=m.alamat||"-";$("maintenanceForm").classList.remove("hidden");$("scanMsg").textContent="✓ Data meter ditemukan"}else $("scanMsg").textContent="Meter tidak ditemukan di MASTER_METER"}catch(e){$("scanMsg").textContent="Gagal: "+e.message}}
async function startScan(){if(!API){$("scanMsg").textContent="Isi URL API di Pengaturan.";return}if(typeof Html5Qrcode==="undefined"){ $("scanMsg").textContent="Scanner belum siap.";return}$("scanPlaceholder").classList.add("hidden");$("startScan").classList.add("hidden");$("stopScan").classList.remove("hidden");scanner=new Html5Qrcode("reader");try{await scanner.start({facingMode:"environment"},{fps:10,qrbox:{width:260,height:150}},async text=>{let n=(String(text).match(/\d{8,20}/)||[String(text)])[0];await stopScan();$("manualMeter").value=n;lookup(n)})}catch(e){$("scanMsg").textContent="Kamera gagal: "+e.message;stopScan()}}
async function stopScan(){if(scanner){try{await scanner.stop()}catch(e){}try{await scanner.clear()}catch(e){}scanner=null}$("startScan").classList.remove("hidden");$("stopScan").classList.add("hidden")}
function getGps(){if(!navigator.geolocation)return;$("gpsText").textContent="Mengambil GPS...";navigator.geolocation.getCurrentPosition(p=>{gps={lat:p.coords.latitude.toFixed(6),lng:p.coords.longitude.toFixed(6),accuracy:p.coords.accuracy.toFixed(1)};$("gpsText").textContent=gps.lat+", "+gps.lng+" (±"+gps.accuracy+"m)"},e=>$("gpsText").textContent="GPS gagal")}
function previewPhoto(){let f=$("fFoto").files[0];if(!f)return;let r=new FileReader();r.onload=e=>{photo=e.target.result;$("preview").src=photo;$("preview").classList.remove("hidden")};r.readAsDataURL(f)}
async function saveRecord(e){e.preventDefault();let d={action:"saveMaintenance",timestamp:new Date().toISOString(),tanggal:new Date().toLocaleDateString("id-ID"),idPelanggan:$("fId").value,nomorMeter:$("fMeter").value,namaPelanggan:$("customerName").textContent,alamat:$("customerAddress").textContent,jenis:$("fJenis").value,kondisi:$("fKondisi").value,kondisiSegel:$("fSegel").value,stand:$("fStand").value,hasilPemeriksaan:$("fHasil").value,keterangan:$("fKet").value,latitude:gps.lat||"",longitude:gps.lng||"",accuracy:gps.accuracy||"",foto:photo};try{let r=await fetch(API,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(d)}),x=await r.json();if(x.ok===false)throw Error(x.error||"Gagal");$("saveMsg").textContent="✓ Maintenance berhasil disimpan";history.unshift(d);localStorage.setItem("simeter_history",JSON.stringify(history));summary();renderTasks()}catch(e){d.pending=true;history.unshift(d);localStorage.setItem("simeter_history",JSON.stringify(history));$("saveMsg").textContent="⚠ Internet gagal. Data disimpan sementara secara offline.";summary()}}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}function escAttr(v){return String(v??"").replace(/'/g,"&#39;")}
