/* RIMPU PLN UP3 Bima - Dashboard Baru v1.4.0 */
(function(){
'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function tile(id,icon,title,desc,cls){return `<button type="button" class="rd-tile ${cls||''}" id="${id}"><span class="rd-icon">${icon}</span><span class="rd-title">${title}</span><span class="rd-desc">${desc}</span><span class="rd-arrow">→</span></button>`}
function render(){const d=$('dashboard');if(!d)return;d.innerHTML=`<div class="rd-wrap">
<div class="rd-hero"><div><div class="rd-kicker">RIMPU PLN UP3 BIMA</div><h2>Dashboard Pemeliharaan Meter</h2><p>Monitoring, pemeliharaan, penugasan dan pelaporan meter transaksi energi.</p></div><div class="rd-date"><span>📅</span><b>${new Date().toLocaleDateString('id-ID',{day:'2-digit',month:'long',year:'numeric'})}</b><small>${USER?.name||USER?.username||'Pengguna'} · ${USER?.role||'PETUGAS'}</small></div></div>
<div class="rd-stats"><div class="rd-stat"><span>▦</span><small>Total Meter</small><b id="rdMeters">—</b><em>Master meter</em></div><div class="rd-stat"><span>🔧</span><small>Pemeliharaan</small><b id="rdHist">—</b><em>Riwayat pekerjaan</em></div><div class="rd-stat"><span>⏱</span><small>Jatuh Tempo</small><b id="rdDue">—</b><em>Perlu perhatian</em></div><div class="rd-stat"><span>✓</span><small>Tugas Terbuka</small><b id="rdTasks">—</b><em>Penugasan aktif</em></div></div>
<div class="rd-section-head"><div><h3>Akses Cepat</h3><p>Pilih menu sesuai pekerjaan Anda.</p></div></div>
<div class="rd-actions">${tile('rpDashMaint','🔧','Pemeliharaan','Input & riwayat pemeliharaan meter','blue')}${tile('rpDashInterval','⚙️','Pengaturan Interval','Atur jadwal & interval pemeliharaan','green')}${tile('rpDashBA','📄','Berita Acara','Buat dan kelola berita acara','indigo')}${tile('rpDashWeather','🌦️','Cek Cuaca','Cuaca berdasarkan lokasi meter','purple')}${tile('rpDashNav','📍','Navigasi','Arahkan ke lokasi meter','orange')}${tile('rpDashReport','📊','Laporan','Rekap dan export data','teal')}</div>
<div class="rd-lower"><section class="rd-panel"><div class="rd-panel-head"><div><h3>Aktivitas Terbaru</h3><p>Riwayat pekerjaan terakhir</p></div><button type="button" class="rd-link" id="rdOpenHistory">Lihat semua →</button></div><div id="rdRecent" class="rd-recent"><div class="rd-loading">Memuat data…</div></div></section><section class="rd-panel"><div class="rd-panel-head"><div><h3>Perhatian</h3><p>Meter yang mendekati jatuh tempo</p></div></div><div id="rdAlerts" class="rd-alerts"><div class="rd-loading">Memuat data…</div></div></section></div></div>`;
load();bind();}
async function load(){try{if(!API)throw Error('URL Web App belum diisi');const [m,h,t]=await Promise.allSettled([request('getMeters',{timeout:20000}),request('getHistory',{timeout:20000}),request('getTasks',{timeout:20000})]);let md=m.status==='fulfilled'&&m.value?.ok?m.value.data||[]:[];let hd=h.status==='fulfilled'&&h.value?.ok?(h.value.data||h.value.rows||[]):[];let td=t.status==='fulfilled'&&t.value?.ok?t.value.data||[]:[];meters=Array.isArray(md)?md:[];history=Array.isArray(hd)?hd:[];tasks=Array.isArray(td)?td:[];const due=meters.filter(x=>x.jatuhTempo&&typeof daysUntil==='function'&&daysUntil(x.jatuhTempo)<=7);$('rdMeters').textContent=meters.length;$('rdHist').textContent=history.length;$('rdDue').textContent=due.length;$('rdTasks').textContent=tasks.filter(x=>!['SELESAI','BATAL'].includes(String(x.status||'').toUpperCase())).length;renderRecent();renderAlerts(due)}catch(e){['rdMeters','rdHist','rdDue','rdTasks'].forEach(id=>{if($(id))$(id).textContent='—'});$('rdRecent').innerHTML=`<div class="rd-empty">Data belum dapat dimuat.<br><small>${esc(e.message)}</small></div>`}}
function renderRecent(){const a=history.slice(0,6);$('rdRecent').innerHTML=a.length?a.map(x=>`<div class="rd-row"><div class="rd-row-icon">🔧</div><div><b>${esc(x.nomorMeter||x[3]||'-')}</b><span>${esc(x.jenis||x.kondisi||x[9]||'Pemeliharaan')}</span></div><time>${esc(x.tanggal||x.timestamp||x[1]||'-')}</time></div>`).join(''):`<div class="rd-empty">Belum ada riwayat pemeliharaan.</div>`}
function renderAlerts(a){$('rdAlerts').innerHTML=a.length?a.slice(0,5).map(x=>{const n=daysUntil(x.jatuhTempo);return `<div class="rd-alert ${n<0?'danger':''}"><span>⚠️</span><div><b>${esc(x.nomorMeter||'-')}</b><small>${n<0?'Terlambat '+Math.abs(n)+' hari':'Jatuh tempo '+esc(x.jatuhTempo)}</small></div></div>`}).join(''):`<div class="rd-empty ok">✓ Tidak ada meter yang mendekati jatuh tempo.</div>`}
function bind(){const map={rpDashMaint:'doMaintenance',rpDashInterval:'doInterval',rpDashBA:'doBA',rpDashWeather:'doWeather',rpDashNav:'doNav',rpDashReport:'doReport'};Object.entries(map).forEach(([id,fn])=>{const b=$(id);if(b)b.onclick=e=>{e.preventDefault();if(window.rimpuDashboardActions?.[fn])window.rimpuDashboardActions[fn]();else if(typeof window[fn]==='function')window[fn]();}});const h=$('rdOpenHistory');if(h)h.onclick=()=>navigate('meters')}
window.renderDashboardNew=render;
const old=window.renderDashboard;window.renderDashboard=function(){render();};
})();
