(function(){
  const escW = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const weatherText = code => ({0:'Cerah',1:'Cerah berawan',2:'Sebagian berawan',3:'Berawan',45:'Berkabut',48:'Kabut tebal',51:'Gerimis ringan',53:'Gerimis',55:'Gerimis lebat',61:'Hujan ringan',63:'Hujan sedang',65:'Hujan lebat',71:'Salju ringan',73:'Salju',75:'Salju lebat',80:'Hujan singkat',81:'Hujan singkat',82:'Hujan sangat lebat',95:'Badai petir',96:'Badai petir + hujan es',99:'Badai petir + hujan es'}[Number(code)] || 'Kondisi tidak diketahui');
  const weatherIcon = code => { code=Number(code); if(code===0)return'☀️'; if(code<=3)return'🌤️'; if(code<=48)return'🌫️'; if(code<=55)return'🌦️'; if(code<=65||code<=82)return'🌧️'; if(code<=86)return'❄️'; return'⛈️'; };
  function safety(code,prob,wind){ code=Number(code); prob=Number(prob||0); wind=Number(wind||0); if(code>=95||prob>=80||wind>=45)return{cls:'danger',label:'🔴 TIDAK DISARANKAN',note:'Periksa kembali kondisi keselamatan sebelum berangkat.'}; if(prob>=50||wind>=30||code>=61)return{cls:'warn',label:'🟡 WASPADA',note:'Siapkan perlengkapan hujan dan perhatikan kondisi lapangan.'}; return{cls:'ok',label:'🟢 CUKUP AMAN',note:'Kondisi cuaca relatif mendukung pekerjaan lapangan.'}; }
  async function getLocationForTask(t){
    const meterNo=String(t.nomorMeter||t.meter||'');
    if(!window.meters?.length){try{const r=await request('getMeters');window.meters=r.data||[];}catch(_) {}}
    const m=(window.meters||[]).find(x=>String(x.nomorMeter)===meterNo)||{};
    let hs=window.history||[];
    if(!hs.length){try{const r=await request('getHistory');hs=r.data||r.rows||[];window.history=hs;}catch(_) {}}
    const candidates=hs.filter(x=>String(x.nomorMeter||x[3]||'')===meterNo && x.latitude && x.longitude);
    const latest=candidates[candidates.length-1];
    if(latest)return{lat:Number(latest.latitude),lon:Number(latest.longitude),address:m.alamat||latest.alamat||''};
    if(m.latitude&&m.longitude)return{lat:Number(m.latitude),lon:Number(m.longitude),address:m.alamat||''};
    const address=String(m.alamat||t.alamat||'').trim();
    if(address){try{const u='https://geocoding-api.open-meteo.com/v1/search?name='+encodeURIComponent(address)+'&count=1&language=id&format=json';const r=await fetch(u);const j=await r.json();const x=j.results&&j.results[0];if(x)return{lat:Number(x.latitude),lon:Number(x.longitude),address:x.name||address};}catch(_) {}}
    return{lat:null,lon:null,address};
  }
  function navTo(loc){if(loc.lat!=null&&loc.lon!=null){window.location.href='geo:'+loc.lat+','+loc.lon+'?q='+loc.lat+','+loc.lon;}else if(loc.address){window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(loc.address),'_blank');}else alert('Lokasi pekerjaan belum tersedia.');}
  async function showWeather(t){
    const body=$('modalBody');if(!body)return;body.innerHTML='<div class="weather-loading">🌦️ Mengambil perkiraan cuaca lokasi...</div>';
    try{const loc=await getLocationForTask(t);if(loc.lat==null||loc.lon==null)throw Error('Koordinat lokasi belum tersedia untuk meter ini.');const url='https://api.open-meteo.com/v1/forecast?latitude='+encodeURIComponent(loc.lat)+'&longitude='+encodeURIComponent(loc.lon)+'&timezone=auto&forecast_days=3&current=temperature_2m,relative_humidity_2m,apparent_temperature,precipitation,weather_code,wind_speed_10m&hourly=temperature_2m,precipitation_probability,weather_code,wind_speed_10m';const r=await fetch(url);if(!r.ok)throw Error('Layanan cuaca tidak merespons.');const j=await r.json();const cur=j.current||{};const h=j.hourly||{};let nowIndex=(h.time||[]).findIndex(x=>new Date(x)>=new Date());if(nowIndex<0)nowIndex=0;const prob=(h.precipitation_probability||[])[nowIndex]??0;const st=safety(cur.weather_code,prob,cur.wind_speed_10m);const rows=[0,1,2,3,4,5].map(i=>{const idx=Math.min(nowIndex+i,h.time.length-1);return `<div class="weather-hour"><b>${new Date(h.time[idx]).toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'})}</b><span>${weatherIcon(h.weather_code[idx])} ${Math.round(h.temperature_2m[idx])}°C</span><span>🌧️ ${h.precipitation_probability[idx]??0}%</span><span>💨 ${Math.round(h.wind_speed_10m[idx]||0)} km/j</span></div>`}).join('');body.innerHTML=`<h2>🌦️ Cuaca Lokasi Kerja</h2><div class="weather-location">📍 ${escW(loc.address||('Koordinat '+loc.lat.toFixed(5)+', '+loc.lon.toFixed(5)))}</div><div class="weather-main"><div class="weather-icon">${weatherIcon(cur.weather_code)}</div><div><b>${Math.round(cur.temperature_2m)}°C</b><div>${escW(weatherText(cur.weather_code))}</div></div></div><div class="weather-grid"><div><small>Kelembapan</small><b>${cur.relative_humidity_2m??'-'}%</b></div><div><small>Hujan</small><b>${prob}%</b></div><div><small>Angin</small><b>${Math.round(cur.wind_speed_10m||0)} km/j</b></div><div><small>Terasa</small><b>${Math.round(cur.apparent_temperature??cur.temperature_2m)}°C</b></div></div><div class="weather-status ${st.cls}"><b>${st.label}</b><div>${st.note}</div></div><h3>Perkiraan beberapa jam ke depan</h3><div class="weather-hours">${rows}</div><div class="actions"><button id="weatherNavBtn" class="primary">🧭 Navigasi ke Lokasi</button><button id="weatherRefreshBtn" class="secondary">↻ Perbarui Cuaca</button></div><small class="weather-source">Prakiraan berdasarkan koordinat lokasi. Data cuaca: Open-Meteo.</small>`;$('weatherNavBtn').onclick=()=>navTo(loc);$('weatherRefreshBtn').onclick=()=>showWeather(t);
    }catch(e){body.innerHTML=`<h2>🌦️ Cuaca Lokasi Kerja</h2><div class="alert danger">${escW(e.message)}</div><div class="actions"><button id="weatherNavFallback" class="primary">🧭 Navigasi ke Lokasi</button></div>`;$('weatherNavFallback').onclick=async()=>navTo(await getLocationForTask(t));}
  }
  function openTaskEnhanced(t){showModal(`<h2>📋 ${escW(t.judul||t.jenis||'Penugasan')}</h2><div class="details-grid"><div class="kv"><small>Nomor Meter</small><b>${escW(t.nomorMeter||t.meter||'-')}</b></div><div class="kv"><small>Petugas</small><b>${escW(t.petugas||t.assignee||'-')}</b></div><div class="kv"><small>Status</small><b>${escW(String(t.status||'OPEN').toUpperCase())}</b></div><div class="kv"><small>Jatuh Tempo</small><b>${escW(t.deadline||t.jatuhTempo||'-')}</b></div></div><div class="actions"><button id="taskWeatherBtn" class="primary">🌦️ Cek Cuaca</button><button id="taskNavBtn" class="secondary">🧭 Navigasi ke Lokasi</button></div><div class="alert">Gunakan cek cuaca sebelum berangkat agar petugas dapat menyiapkan perlengkapan dan mempertimbangkan kondisi lapangan.</div>`);$('taskWeatherBtn').onclick=()=>showWeather(t);$('taskNavBtn').onclick=async()=>navTo(await getLocationForTask(t));}
  window.loadTasks=async function(){$('tasksView').innerHTML=`<div class="toolbar">${['SUPER_ADMIN','ADMIN','SUPERVISOR'].includes(USER?.role)?'<button id="newTaskBtn" class="primary">+ Penugasan Baru</button>':''}<button id="refreshTasks" class="secondary">↻</button></div><div id="taskList">Memuat...</div>`;if($('newTaskBtn'))$('newTaskBtn').onclick=newTask;$('refreshTasks').onclick=loadTasks;try{const params=['SUPER_ADMIN','ADMIN','SUPERVISOR'].includes(USER?.role)?{}:{username:USER?.username||''};const r=await request('getTasks',{params});if(!r||!r.ok)throw Error(r?.error||'Gagal mengambil penugasan.');tasks=r.data||[];if(!meters.length){try{const mr=await request('getMeters');meters=mr.data||[];}catch(_) {}}$('taskList').innerHTML=tasks.map((t,i)=>`<button class="task weather-task-card" data-task-index="${i}" type="button"><div class="meter-head"><div><b>${esc(t.nomorMeter||t.meter||'-')}</b><div class="meta">${esc(t.judul||t.jenis||'Penugasan')}</div></div><b class="badge">${esc(String(t.status||'OPEN').toUpperCase())}</b></div><div>${esc(t.petugas||t.assignee||'-')}</div><small>${esc(t.deadline||t.jatuhTempo||'')}</small><div class="weather-task-actions"><span>🌦️ Cek Cuaca</span><span>🧭 Navigasi</span></div></button>`).join('')||'<div class="empty">Belum ada tugas.</div>';document.querySelectorAll('.weather-task-card').forEach(card=>card.onclick=()=>openTaskEnhanced(tasks[Number(card.dataset.taskIndex)]));}catch(e){$('taskList').innerHTML='<div class="alert danger">'+esc(e.message)+'</div>';}};
})();
